name: Full CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # TẦNG 1: CONTINUOUS INTEGRATION (TEST)
  unit-test:
    name: 🧪 1. Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run Jest Test
        run: npm test

  # TẦNG 2: BUILD & PACKAGE
  build-package:
    name: 📦 2. Build Artifact
    needs: unit-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Build Web Dist
        run: npm run build

      - name: Upload Page Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'dist/'

  # TẦNG 3: CONTINUOUS DEPLOYMENT (DEPLOY)
  deploy-production:
    name: 🚀 3. Deploy to Live Server
    needs: build-package
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
